// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaMGPSt690ID89PFmCImN40OGf2WZdEok',
    appId: '1:969203976543:web:2f3a323850c0c99b7a4eea',
    messagingSenderId: '969203976543',
    projectId: 'atelier4-elfardwiam',
    authDomain: 'atelier4-elfardwiam.firebaseapp.com',
    storageBucket: 'atelier4-elfardwiam.firebasestorage.app',
    measurementId: 'G-HM6VWQKBJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIp8deLoj740GngGj_hel51hcdA_5Umds',
    appId: '1:969203976543:android:49e857ad5830d31f7a4eea',
    messagingSenderId: '969203976543',
    projectId: 'atelier4-elfardwiam',
    storageBucket: 'atelier4-elfardwiam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACaZUIW567KcE0w52l2YKR9ati4VC7qr8',
    appId: '1:969203976543:ios:a063f6e6157232187a4eea',
    messagingSenderId: '969203976543',
    projectId: 'atelier4-elfardwiam',
    storageBucket: 'atelier4-elfardwiam.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

}